name: "🐛 Bug Report"
description: Create an issue for a bug report.
title: "bug: <title>"
labels: [
  "Bug",
  "New Issue"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Enter a clear issue description.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction"
      description: Steps to reproduce, if known.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: Attach screenshots, if helpful.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Paste relevant log output, if any.
      render: bash
    validations:
      required: false