name: "⭐ Feature Request"
description: Create an issue for a feature request.
title: "feat: <title>"
labels: [
  "Feature",
  "New Issue"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "# Summary"
      description: Briefly describe the request.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: "# Requirements"
      description: List the request's requirements.
    validations:
      required: true