name: "⭐ Feature Request"
description: Create an issue for a feature request.
title: "feat: <title>"
labels: [
  "Feature",
  "New Issue"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Please provide a brief explanation of the request.
    validations:
      required: true