name: Lint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: dotnet format style Aurora.sln --verify-no-changes
