name: Lint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Download and install tModLoader
      run: |
        cd ..
        mkdir ./tmod
        cd ./tmod
        
        wget https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip
        unzip tModLoader.zip
        rm tModLoader.zip
        
        cd ..

    - name: Create tModLoader .targets file
      run: |
        touch tModLoader.targets
        
        echo '<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project=".\tmod\tMLMod.targets" />
        </Project>' > tModLoader.targets
        
        cd ./Aurora
        
    - name: Lint
      run: dotnet format style PathOfTerraria.sln --verify-no-changes
